### ISSUE TITLE
dist training spwn no rank args

### ISSUE THREAD

**Issue by jayagami** [lucidrains/lightweight-gan#114]
The training process looks fine, but I noticed that a parameter rank is missing from the line 185, `mp.spawn run_training`, is this correct?

https://github.com/lucidrains/lightweight-gan/blob/b7c34d587d029177ddc641f42b2604506352dfb2/lightweight_gan/cli.py#L180-L187

**Comment by iScriptLex** [comment]
Yes, it's correct.
When `torch.multiprocessing.spawn` calls `run_training`, it's called in the format `run_training(ind, *args)`, where `ind` is the process index (see pytorch documentation: https://pytorch.org/docs/stable/multiprocessing.html ).
That's why the function has one more parameter than the number of arguments passed to it in line 185.

**Comment by jayagami** [comment]
> Yes, it's correct. When `torch.multiprocessing.spawn` calls `run_training`, it's called in the format `run_training(ind, *args)`, where `ind` is the process index (see pytorch documentation: https://pytorch.org/docs/stable/multiprocessing.html ). That's why the function has one more parameter than the number of arguments passed to it in line 185.

Thanks for your replying.
Sorry for I missed it!
